export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const RESET_CURRENT_LOCATION = 'RESET_CURRENT_LOCATION';

export const APPLY_NEW_FILTER = 'APPLY_NEW_FILTER';
export const FOCUS_MAP  = 'FOCUS_MAP';